# Generated by Django 5.1.1 on 2024-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Gestor', 'Gestor territorial'), ('Director', 'Director'), ('Ciudadano', 'Ciudadano'), ('Admin', 'Administrador')], default='Ciudadano', max_length=20)),
            ],
        ),
    ]
