# Generated by Django 5.1.1 on 2024-10-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_usuarios_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol', models.CharField(choices=[('Gestor', 'Gestor territorial'), ('Director', 'Director'), ('Ciudadano', 'Ciudadano'), ('Admin', 'Administrador')], max_length=20, primary_key=True, serialize=False)),
                ('ver', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('eliminar', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuariosDelRol', to='loginapp.roles'),
        ),
    ]
