# Generated by Django 5.1.1 on 2024-10-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_roles_alter_usuarios_email_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
